# Generated by Django 4.1.6 on 2023-02-20 20:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_meal_restaurnat_alter_meal_price_alter_meal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_on', models.DateField(auto_now_add=True)),
                ('Address', models.TextField(blank=True)),
                ('Price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cart')),
                ('Meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.meal')),
            ],
        ),
    ]
