# Generated by Django 4.1.6 on 2023-02-11 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to=menu.models.upload_path)),
                ('Name', models.CharField(max_length=42)),
                ('Body', models.TextField(blank=True)),
                ('Price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
        ),
    ]
